name: deploy
on:
  release:
    types: [published]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: setup node
        uses: actions/setup-node@v2
        with:
          cache: npm
          registry-url: 'https://registry.npmjs.org'

      - name: npm install video.js
        env:
          VJS_VERSION: ${{ github.event.tag_name }}
        run: npm install video.js@`echo $VJS_VERSION | cut -d 'v' -f 2`
